#!/bin/sh
# Copyright (C) 2000-2017 Synology Inc. All rights reserved.

case $1 in
	start)
		/sbin/insmod $SYNOPKG_PKGDEST/xpenology-kernel-symbols/xpenology.ko
		exit 0
	;;
	stop)
		/sbin/rmmod $SYNOPKG_PKGDEST/xpenology-kernel-symbols/xpenology.ko
		exit 0
	;;
	status)
		/sbin/lsmod | grep xpenology && exit 0 || exit 3
	;;
	killall)
        ;;
	log)
		exit 0
	;;
esac

